spring.application.name=management

# PostgreSQL DB configuration
spring.datasource.url=jdbc:postgresql://dpg-d4p8sc6mcj7s73fue6mg-a:5432/emp_management_xzwr
spring.datasource.username=emp_management_xzwr_user
spring.datasource.password=OYi5tMMQhaSOHpjdq5IdkUc23OCJ3Vpw
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Hibernate/JPA Configuration

server.port=${PORT:8080}
server.servlet.context-path=/
